MDScreen:
    GridLayout:
        cols: 2
    
        MapView:
            id: map
            lat: 14.466762
            lon: 120.974886
            zoom: 10
        ScrollView:
            MDList:
                ThreeLineListItem:
                    id:userinfo
                    text: 'Loading'
                    secondary_text: '...'
                    tertiary_text: '...'  
            